### ISSUE TITLE
BrepLoopType and other Brep subclasses are strings instead of Enum types

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/specklepy#133]
In C#, currently all `Brep` subclasses like `BrepLoop` and `BrepTrim` have a `type` property that is an enum. These are serialised as integers in the C# SDK.

The current object model in Python deserialises them as `str`, which doesn't cause an issue when receiving those `Breps`, but it prevents them from being sent from Python and received back in other C# connectors.

Pinging @AntoineDao as he may be interested in commenting about this. Changing this would break any `Brep` implementations that assume the `type` to be `str`.

Here's the `type` in the `BrepLoop` in C#:
https://github.com/specklesystems/speckle-sharp/blob/e08e51db07d532e7553d0904a43c408760a910b2/Objects/Objects/Geometry/Brep.cs#L310

and the `BrepLoopType` implementation:
https://github.com/specklesystems/speckle-sharp/blob/e08e51db07d532e7553d0904a43c408760a910b2/Objects/Objects/Geometry/Brep.cs#L412-L420

Here's the type of the `BrepLoop`
https://github.com/specklesystems/specklepy/blob/f49491611f82aa711bc44b856acd35b027d001c5/specklepy/objects/geometry.py#L510

It looks like `BrepTrimType` does exist as an enum but it's not being used in the class:
https://github.com/specklesystems/specklepy/blob/f49491611f82aa711bc44b856acd35b027d001c5/specklepy/objects/geometry.py#L542

The current error we're getting is **Cannot deserialise string to BrepLoopType**.

To reproduce: 
1. send a `Brep` from Rhino/GH.
2. receive that brep in python
3. send it back to speckle
4. try to receive it in Rhino/GH.

**Comment by izzylys** [comment]
As discussed w the three of us while debugging hatches, perhaps we want to rethink how the serialisation is happening from the C# side as well since having ints represent categories is usually not super helpful. We should come to a decision before aligning everything.

**Comment by clairekuang** [comment]
Also linked to speckle-sharp issue https://github.com/specklesystems/speckle-sharp/issues/862

**Comment by izzylys** [comment]
closed with #200
