### ISSUE TITLE
Commit with branchName=None

### ISSUE THREAD

**Issue by mortenengen** [specklesystems/specklepy#142]
### Expected vs. Actual Behavior

When a commit is fetched using `client.commit.get()`, it gets assigned a proper value for the `branchName` attribute. However, when it is fetched using `client.commit.list()`, `branchName` is only set to the default value `None`.

### Reproduction Steps & System Config

specklepy v2.4.2

1. Create commits in one or more branches on a stream.
2. Fetch the commits on the stream, e.g. `commits = client.commit.list(stream_id=stream_id)`.
3. Print the branchName attribute, e.g. `for commit in commits: print(commit.branchName)`

### Proposed Solution

The `branchName` attribute is missing in the gql query in `client.commit.list()`.

I have added it and tested it locally, and am happy to create a PR.

**Comment by izzylys** [comment]
hey morten, nice to see you around here 😊

oopsie good spot - totally just missed it in the query! i've just popped it in and added it to the commit model repr for fun. 

you should be able to install v2.4.3 with this fix very soon. thanks a lot for spotting and reporting this issue! 🚀
