### ISSUE TITLE
Please upgrade the ujson dependency, which has a CVE

### ISSUE THREAD

**Issue by trygveaa** [specklesystems/specklepy#160]
There was recently posted a CVE for ujson >= 4.0.2, < 5.1.0 for an out-of-bounds write: https://github.com/advisories/GHSA-fh56-85cw-5pq6

This is fixed in ujson 5.1.0, but since specklepy depends on ujson ^4.3.0, that isn't used. Could you please upgrade ujson to version 5.x?

The only breaking change in ujson 5.x is that they dropped support for Python 3.6, which was EOL a month ago.

**Comment by izzylys** [comment]
see #190
