### ISSUE TITLE
🦾  `stl.send()` and poss other file upload helpers

### ISSUE THREAD

**Issue by izzylys** [specklesystems/specklepy#187]
add a helper that will allow users to just convert `file_to_speckle` for ez script file uploads eg for c4d and maya

**Comment by gjedlicska** [comment]
It would be reasonable to move all file type parsing logic into an [extra](https://stackoverflow.com/questions/52474931/what-is-extra-in-pypi-dependency) dependency in specklepy. The logic is already there, and used in the speckle-server [repo](https://github.com/specklesystems/speckle-server/blob/main/packages/fileimport-service/obj/import_file.py#L28).
