### ISSUE TITLE
🐘 Hold deserialized objects in mem in order to return single instances of objs with the same `id`

### ISSUE THREAD

**Issue by izzylys** [specklesystems/specklepy#191]
v2 serializer in core made this change and it wasn't propagated to py. requested by tom here:

https://speckle.community/t/circular-references-detaching-objects-in-python/3071

will need to adjust brep deserialisation and test for any weirdness in blender with this change (are there any other objs that are likely to have the same id where this could be an issues?)

see https://github.com/specklesystems/speckle-sharp/pull/823

**Comment by AlanRynne** [comment]
As far as I'm aware, BREPs are the only place where this is an issue we need to carefully consider the way to deal with this. No other class uses the `OnDeserialized` attribute.
