### ISSUE TITLE
Spelling mistakes on some documentation

### ISSUE THREAD

**Issue by donheshanthaka** [specklesystems/specklepy#217]
Hey there, i have found some spelling mistakes in your documentation, but before contributing i just want to clarify since it's no code contribution, would it be marked as spam? if not and it is accepted for hacktoberfest 2022. does that mean it can be a valid PR for not only this repo but in other repos under specklesystems as well?

**Comment by gjedlicska** [comment]
Hello @donheshanthaka,

thank you for your interest. While we see the value in fixing these issues, PR-s are welcome, but they do not fit in our hacktoberfest categories.

We've created a [project ](https://github.com/orgs/specklesystems/projects/14/views/1)specifically for hacktoberfest, that lists the no-code contributions we are looking for. You are more than welcome to work on those issues :)
