### ISSUE TITLE
"Invalid credentials" upon sending - Transport getting the wrong account from Manager

### ISSUE THREAD

**Issue by KatKatKateryna** [specklesystems/specklepy#224]
Sending to the stream gives the error: "Speckle : Error sending data: Invalid credentials - cannot send objects to server https://speckle.xyz/"

Potential issue: if manager has multiple accounts on the same server, then the Transport derived using "ServerTransport(client, streamId)", might get the wrong account (if it was first in the order) and then fail with above error. 

Solved by removing extra account from Manager.

**Comment by gjedlicska** [comment]
How is this handled in Core @AlanRynne ?

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
