### ISSUE TITLE
use namedtuple for multiple returns

### ISSUE THREAD

**Issue by majidaldo** [specklesystems/specklepy#236]
https://github.com/specklesystems/specklepy/blob/67499ab20c754b4f51e8cf3746d4aba745d3af70/src/specklepy/serialization/base_object_serializer.py#L96

**Comment by gjedlicska** [comment]
If you want to have a go at this @majidaldo go ahead. Since this is method is mostly used internally, the little added documentation benefit of a namedtuple never actually made sense for me here.
