### ISSUE TITLE
Objects: Enforce alignment of dotnet and python SDKs with tests

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/specklepy#237]
Mirrored from specklesystems/speckle-sharp#1999

# Description

This is born out of @gjedlicska's fights in `specklepy`, and the realisation that we are constantly miss-aligning both our SDKs in many subtle but important ways.

Minor changes in how our objects are serialised, the type of their properties or their nullability, will have breaking effects in the other SDKs, and it's quite a difficult thing to keep track of.

This greatly affects the stability of our product, as workflows that depend on _cross-language_ to work (Rhino -> Blender, QGIS -> Unity, ...) will most likely break when the definition of objects is not the same across `python` and `dotnet`.

# Proposed solution

A good solution for this would be to have some way of testing if the implementation on both sides is correct. i.e:
- That the object exists in the SDK
- That the object contains the same properties in it's definition
- That the object properties have matching Types and nullability

This would require the creation of some sort of "conformance testing" that would work across languages.

Our initial idea would be to:
- Consider `speckle-sharp` the main **source of truth** as for what our objects are.
- Generate some sort of `type definitions` from speckle-sharp that would be _language agnostic_ (this doesn't have to be a json schema in particular... but it would be nice)
- Use those generated `type definitions` to verify that **all objects** across programming languages are defined in a consistent way.

Furthermore, we could add a layer of cross-language validation on top of this with some _mocked values_:
- Using a mock library (in python, dotnet or both?) to generate a set of object instances for each available class.
- Serialise those instances into JSON
- Verify that the generated JSON can be deserialised in the other language, and that the type/values are consistent.
- This could be chained up to verify "round-tripping" of objects between specklepy and speckle-sharp works consistently too.

# Examples of why this is necessary

- Misaligned SDKs can be a major source of problems, and will affect the overall "quality" of what we deliver. It's very easy to introduce new changes that are single-sided, very difficult to catch them down the line in a different language than the original.
- https://speckle.community/t/child-class-speckle-type-deserialization-issue/3803/6
- More to come

**Comment by majidaldo** [comment]
@AlanRynne , if you have an equivalent type system checking data on both ends, why would you need the tests? In c#, it's essentially the compilation process (?). If you go through json, as I can see in the proposal, then serializing from a json-schema-enforced json should just do the trick eh?

**Comment by gjedlicska** [comment]
@majidaldo this is a bit more complex topic. We have to make sure the object schemas are on par in all of our SDK-s, which are currently C# and python. We need a way to ensure, that at-least the objects that are implemented in all languages are conforming to the schema.

On one level this is a profane problem, were we are humans and we cannot do a perfect job in keeping our object models in sync.

**Comment by majidaldo** [comment]
> @majidaldo this is a bit more complex topic. We have to make sure the object schemas are on par in all of our SDK-s, which are currently C# and python. We need a way to ensure, that at-least the objects that are implemented in all languages are conforming to the schema.
> 
> On one level this is a profane problem, were we are humans and we cannot do a perfect job in keeping our object models in sync. We do have some ideas on how to make this work, but if you have any ideas or suggestions how to pull this off, we'd love to hear it.

This issue deals with tests.  Would there be a discussion topic?

**Comment by majidaldo** [comment]
id discrepancy. 

Revit > speckle > server > python sdk (objects) > json (dict).  the ids in the json do not equal the ids that i see in the server. is this expected behavior?

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
