### ISSUE TITLE
Transform Logic is misaligned from Sharp

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/specklepy#246]
`ITransformable` is not implemented in SpecklePy

There was an attempt to add this https://github.com/specklesystems/specklepy/pull/146
This PR is in an unknown state, is not a current priority to get merged in, so closed for now until we (or users) need these functions.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
