### ISSUE TITLE
Please allow get number version current

### ISSUE THREAD

**Issue by chuongmep** [specklesystems/specklepy#255]
## Describe the solution you'd like

I want package support get current version like numpy : 

```py
import numpy as np 
np.version.version
```
With specklepy, I hope it can works : 
```py
import specklepy as sp
sp.version.version
```

## Describe alternatives you've considered

This will be useful when I share some code by jupyter notbook for user, easy to help user view correct version don't need check pip package

**Comment by KatKatKateryna** [comment]
Hi @chuongmep , you can get the package version using importlib: 
`from importlib.metadata import version
version('specklepy')`

**Comment by chuongmep** [comment]
> This just a temp solution for that, thank you @KatKatKateryna  !

**Comment by gjedlicska** [comment]
@KatKatKateryna 's answer is the official way of doing version checks so closing this
