### ISSUE TITLE
Include coreversion in mixpanel analytics

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/specklepy#261]
For mixpanel analytics in sharp, we are including a semver of core as a custom prop to every event
I think it would be quite useful to have this in specklepy also.
Right now, we have no way to know how many users are still using old versions of specklepy.

Potentially related to https://github.com/specklesystems/specklepy/issues/207

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
