### ISSUE TITLE
`client.streams.list` returns (not raises) an exception

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/specklepy#262]
SpecklePY and Blender connector users are reporting problems when stream requests are failing.
`TypeError: ‘SpeckleException’ object is not iterable` 

This is because `make_request` will return (not raise) exceptions.
The `streams.list` function is typed to return `List[Stream]` which it does for successful requests, but for unsuccessful requests, the exception will be returned, causing the above exception message when trying to iterate through the return value.

https://speckle.community/t/typeerror-speckleexception-object-is-not-iterable/4946
https://speckle.community/t/speckleexception-could-not-get-the-requested-stream/4958/4

Question:
- Can we make it so these exceptions are raised rather than returned?

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
