### ISSUE TITLE
Core/Objects: Move Collection class to `Core` instead.

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/specklepy#271]
From speckle-sharp: https://github.com/specklesystems/speckle-sharp/pull/2424

Collections was moved to Core as we needed it to be available outside of the "Kit" for several of our connectors (Grasshopper, Dyn, and I think others)

This should be reflected in our python SDK and any connector depending on it.

**Comment by KatKatKateryna** [comment]
https://github.com/specklesystems/specklepy/pull/269
