### ISSUE TITLE
Manage dependencies clash with gql, request-toolbelt and urllib3

### ISSUE THREAD

**Issue by KatKatKateryna** [specklesystems/specklepy#280]
Example user issue: https://speckle.community/t/qgis-graphql-error/6154/11 (another issue with the same combo of libraries https://speckle.community/t/unable-to-install-speckle-qgis-on-m1-mac/5810/6)

Cause: 
The latest releases of the two libraries (request-toolbelt and urllib3) are incompatible, as reported here https://stackoverflow.com/a/76177575 
gql library that specklepy is using is relying on requests and requests-toolbelt. 
Although universal python installer ensures specific version of every module (e.g. urllib3<=1.26.16), some software (e.g. QGIS) imports request library from the original Python setup (probably imported before Speckle connector is loaded) with possibly incompatible version.

To do:
Look into the use of gql module relying on request-toolbelt, which is then relying on urllib3.

**Comment by KatKatKateryna** [comment]
More details: 

- gql library [fixed the issue](https://github.com/graphql-python/gql/issues/412) by restricting to urllib3<2.0
- request-toolbelt [released 1.0.0](https://github.com/requests/toolbelt/blob/master/HISTORY.rst#100----2023-05-01) to support urllib 2.x

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
