### ISSUE TITLE
`units` prop on `Base` misaligned with speckle-sharp

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/specklepy#281]
Misaligned `units` property on `Base`

In SpecklePY `Base` contains a `units` property
In Sharp, `units` is only used for geometry and primitives.

In py, this leads to confusing object json, where many non-geometry objects have a `none` units property. Including `DataChunk` objects`s  🤦‍♂️

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
