### ISSUE TITLE
Bring back unit testing for all supported python versions

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/specklepy#284]
#283 removed the integration test matrix for anything that wasn't 3.11 python.

This was due to some difficulties we were having in getting ubuntu to accept other versions and successfully restore packages using `poetry`.

For now, integration testing is only being performed in 3.11, but we should add back 3.7 and onwards.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
