### ISSUE TITLE
Possible pydantic issue

### ISSUE THREAD

**Issue by Haunfelder** [specklesystems/specklepy#294]
https://github.com/specklesystems/specklepy/blob/a5096c41ca302c80bf03d9d465beedeeae72ea37/src/specklepy/transports/server/server.py#L53C44-L53C44

I believe the type check for a "requests.Session" instance causes issues with pydantic because the Session object can't be validated. I think this could either be removed, or a line could be added to the ServerTransport pydantic config to allow arbitrary types (see link below). If this seems right, I'm happy to submit a pull request for either change.

https://docs.pydantic.dev/latest/usage/model_config/#arbitrary-types-allowed

**Comment by gjedlicska** [comment]
Thanks for the report @Haunfelder.

You are correct, this is a mis implementation in our sdk.
I've created a [PR](https://github.com/specklesystems/specklepy/pull/296) to potentially fix this

**Comment by Haunfelder** [comment]
Wow, that was quick. Thanks @gjedlicska!

**Comment by gjedlicska** [comment]
Hey @Haunfelder we've also pushed out a new release `2.16.1` with the fix.

Could u confirm, that it fixes your issue?

**Comment by Haunfelder** [comment]
That fixed it. I appreciate the quick turnaround!
