### ISSUE TITLE
SpeckleException: Cannot set 'Spiral.turns'

### ISSUE THREAD

**Issue by dlincoln** [specklesystems/specklepy#301]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Specklepy >=2.11.0 exception (<=2.9.1 no exception)

## Describe the bug

Since version 2.11.0, I get the following exception when passing Civil3D alignment spiral turns values which are originated as floats:

SpeckleException: Cannot set 'Spiral.turns':it expects type 'typing.Optional[int]',but received type 'float'

I’m happy to fix/contribute if it can be confirmed if/why spiral turns should be restricted to integer values or not. Many thanks!

## To Reproduce

Civil3D Alignment/Corridor (with spirals) -> Civil3D Connector -> Speckle (Public or Private) -> Specklepy (speckle.transfer.receive)

## Expected behavior

TBC

### Desktop (please complete the following information):

- OS: Win 10

## Failure Logs

\Lib\site-packages\specklepy\objects\base.py", line 448, in _type_check
    raise SpeckleException(
specklepy.logging.exceptions.SpeckleException: SpeckleException: Cannot set 'Spiral.turns':it expects type 'typing.Optional[int]',but received type 'float'

**Comment by gjedlicska** [comment]
hey @dlincoln 

this issue should be fixed in #308 and release `2.17.4`.
Would u mind testing the new release?

**Comment by dlincoln** [comment]
Many thanks!
On further testing I discover a similar type mismatch bug on another Spiral attribute:
SpeckleException: Cannot set 'Spiral.spiralType':it expects type 'typing.Optional[specklepy.objects.geometry.SpiralType]',but received type 'int'

**Comment by JR-Morgan** [comment]
Hi @dlincoln 
Were thinking https://github.com/specklesystems/specklepy/pull/329 will have fixed the issue you've reported.
version `2.18.2` of specklepy includes this, and will be bundled with our connectors when we make a `2.18` release candidate sometime this week. 

I'll close this ticket now, Please can you test to see if this fully resolves your issue, and reopen if necessary.
