### ISSUE TITLE
👩‍💻 Dev Enhancements: Code Style, Linting, Commit Format, etc

### ISSUE THREAD

**Issue by izzylys** [specklesystems/specklepy#52]
It has been brought up that some enforcement of code style, linting, and commit formatting would be a nice enhancement to this project. While this is a low priority at the moment, it is totally something I agree with eventually implementing.

I am reluctant to be very strict about this to avoid too much overhead and complexity for new contributors to the project, but some general guidelines would be fab and are open for discussion.

On code style, I am fiercely loyal to [black](https://github.com/psf/black) as you can tell from the current codebase and you'll have to put up a very strong argument for me to waver on this. On the rest, it's pretty flexible.

Commit formatting follows commitizen somewhat loosely as do the rest of the `specklesystems` projects. Linting is up in the air - we are currently using pylint for no better reason than that I am used to it so this can totally be changed.

**Comment by gjedlicska** [comment]
This has already been mostly fixed since then
