### ISSUE TITLE
Base model deserializer fails for mandatory __init__ arguments

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/specklepy#59]
### Expected vs. Actual Behavior

This is a new issue that arises after solving #50 via #58.

Given a model below that subclasses the speckle `Base` type, it can only be deserialized by the `BaseObjectSerializer`

```python
from speckle.objects.base import Base
from speckle.api import operations

class FakeBase(Base):
    """Just a test class type."""
    foo: str

if __name__ == "__main__":
    serialized = operations.serialize(fake_model)
    # this fails to deserialize the mandatory arg `foo`
   # because BaseObjectSerializer.recompose_base() assumes to initialize a new object without arguments.
    deserialized = operations.deserialize(serialized)

    assert fake_model.get_id() == deserialized.get_id()

``` 

### Proposed Solution (if any)

Not really sure about a short term fix, but when loading objects with json.loads() the object hook method could be used to directly parse into the type. I'm not 100% on all the recompose step implications yet.

**Comment by izzylys** [comment]
In the short term, this is solved by adding a parameter-less constructor to the derived class. This is already a stipulation in `speckle-sharp` thanks to newtonsoft, so I don't see it as an onerous thing to ask for in the docs. 

In the longer term though, this would be a nice to have so we're leaving the issue open as an enhancement.
